packages:
  - docs
  - __tests__/*

autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
  - simple-git-hooks

overrides:
  esbuild: latest
  rolldown: latest
  vite: npm:rolldown-vite@latest

patchedDependencies:
  '@types/markdown-it-attrs@4.1.3': patches/@types__markdown-it-attrs@4.1.3.patch
  '@types/mdurl@2.0.0': patches/@types__mdurl@2.0.0.patch
  markdown-it-anchor@9.2.0: patches/markdown-it-anchor@9.2.0.patch
  markdown-it-attrs@4.3.1: patches/markdown-it-attrs@4.3.1.patch

shellEmulator: true
