packages:
  - docs
  - __tests__/*

allowBuilds:
  playwright-chromium: true
  simple-git-hooks: true

autoInstallPeers: false

ignoreWorkspaceRootCheck: true

minimumReleaseAge: 1440

overrides:
  esbuild: '-'

patchedDependencies:
  vue-sfc-transformer: patches/vue-sfc-transformer.patch

shellEmulator: true

strictPeerDependencies: true
