packages:
  - docs
  - __tests__/*

autoInstallPeers: false

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
  - simple-git-hooks

overrides:
  ora>string-width: ^5

shellEmulator: true
