name: Close stale issues and PRs
on:
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: -1
          stale-issue-label: stale
          stale-pr-label: stale
          # action has a bug that keeps removing the stale label from stale PRs
          # it's thinking that the PR is updated when the stale label is added
          remove-pr-stale-when-updated: false
          operations-per-run: 1000
